public class anotherRamdomClass {
    //~ Fields here is a quick test for sync.................................

    //~ Constructors ..........................................................

    //~Public  Methods ........................................................

}
